### ISSUE TITLE
CSS chybí a/nebo nepomáhá

### ISSUE THREAD

**Issue by senkyr** [sps-trutnov/projekt-4ep-evidence#109]
Ze všech CSS stylů funguje jenom jeden - a ne moc.

**Comment by senkyr** [comment]
CSS se o hodně zlepšilo. Jediné, co ještě chybí, je:
- profil v dark modu
- profil ve vlasak modu

**Comment by DanSamek** [comment]
Na administraci chybí styl?

**Comment by senkyr** [comment]
Ano. Na administraci chybí styl. Nebo funguje divně.

**Comment by senkyr** [comment]
Administrace už CSS má. Ještě bych rád, aby v něm byly vizuálně oddělené jednotlivé sekce, viz obrázek.
![image](https://user-images.githubusercontent.com/11968410/213405872-a36c47e9-0155-4e82-ac7c-3fcc50273c01.png)

**Comment by DanSamek** [comment]
Rozdělení sekcí přidáno.

**Comment by senkyr** [comment]
Paráda 👍 

Šlo by (bezbolestně) něco takového udělat i v sekci vytváření?

![obrazek](https://user-images.githubusercontent.com/11968410/213988212-84d9fdcb-768c-433e-a8a3-20c2991f01d5.png)

**Comment by DanSamek** [comment]
Je to tam.
