### ISSUE TITLE
Vytváření projektů je nepřehledné

### ISSUE THREAD

**Issue by senkyr** [sps-trutnov/projekt-4ep-evidence#110]
"Vytvoření projektu" v menu slučuje vytváření projektů, položek kategorií a kategorií - a to pozpátku, než jak by se v praxi využívaly.

Daleko lepší by bylo tyto tři formulář rozdělit do samostatných view a odkazovat je z menu jednotlivě.

**Comment by DanSamek** [comment]
Rozdělení do samostatných views mi přijde zbytečné, to by se člověk uklikal..
