### ISSUE TITLE
Nelze vytvořit projekt bez vyplnění všech položek

### ISSUE THREAD

**Issue by senkyr** [sps-trutnov/projekt-4ep-evidence#111]
Vytvoření projektu vyžaduje vyplnění všech položek - včetně těch, které na začátku projektu vyplněny být nemohou (úspěchy).

Jediné povinné položky by měly být název projektu, popis, vedoucí a stav.

**Comment by DanSamek** [comment]
Client/Controller je ready, potřeba upravit DB
