### ISSUE TITLE
Menu Profil obsahuje věci nesouvisející s profilem

### ISSUE THREAD

**Issue by senkyr** [sps-trutnov/projekt-4ep-evidence#134]
V menu Profil by měl být uživatel schopný pracovat se svými uživatelskými údaji. V ideálním případě i spravovat projekty, jejichž je vedoucím. Admin by měl být schopný **v jiném menu** (např. Admin) spravovat všechny projekty a ostatní data - uživatele, kategorie, položky kategorií.

Pikantní je, že _něco jako_ menu Admin existuje - ale je to jen neklikatelná informace o přihlášeném uživateli.

Představuju si, že:
1. každý uživatel (admin, neadmin) bude v menu **Profil** spravovat svoje uživatelské údaje (a svoje projekty)
2. admin bude v menu **Administrace** moci spravovat všechno (projekty, uživatele, kategorie, položky kategorií)
3. informace o přihlášeném uživateli se nebude tvářit jako položka menu (třeba úplně vlevo místo _EvidenceProject_)

![profil_vs_admin](https://user-images.githubusercontent.com/11968410/211753067-582ad9ee-8162-4216-ab7d-f99697011813.png)

**Comment by DanSamek** [comment]
Profil je úspěšně rozdělen na "Profil" a "Administrace".
Uživ. jméno je místo "EvidenceProject".
