### ISSUE TITLE
Kategorie Typ, Stav, Technologie mají být u projektu napevno

### ISSUE THREAD

**Issue by senkyr** [sps-trutnov/projekt-4ep-evidence#138]
Frontend momentálně umožňuje do kategorie **Stav** zadat nějakou úplně jinou kategorii, to samé pro **Typ** a **Technologie**. Tyto tři kategorie by měly být dopředu dané, nemůžu si do kolonky **Stav** vybrat kategorii **ABCD** apod.

Všechny další kategorie, které si administrátor vytvoří, by mělo být možné dodatečně k projektu přidávat, ale ne jimi nahrazovat tyto tři stěžejní.

![image](https://user-images.githubusercontent.com/11968410/213407738-4d9787f1-651d-45bf-925b-f45dfa38c6b7.png)

**Comment by kettner25** [comment]
Hotovo
