### ISSUE TITLE
Backend umožňuje více technologií zároveň, frontend ne

### ISSUE THREAD

**Issue by senkyr** [sps-trutnov/projekt-4ep-evidence#139]
Přestože na úrovni databáze jsme na to připraveni, frontend neumožňuje při vytváření projektu nastavit více různých technologií. To je ale úplně běžná situace - z něčeho projekt postavím, něčím ho ovládám, v něčem píšu firmware atd.

**Comment by kettner25** [comment]
Frontend více technologií umožňuje, pouze byl výběr nepřehledně interpretovaný -> lze vybírat pomocí shift a kliknutím na více položek -> nyní po kliknutí přehlednější možnost výběru
