### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by pachnik** [sps-trutnov/projekt-4ep-evidence#18]
zobrazit názvy nahraných souborů v Create.cshtml

**Comment by Spetlova** [comment]
názvy jsem zobrazila, ale teď se tam zobrazují dvakrát (u inputu se ukazuje se buď název souboru, nebo počet. Asi bych to celé skryla). To už je asi problém css týmu.

**Comment by Veverka-S** [comment]
zkusím se na to podívat, hned jak budu mít možnost
